spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.60:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.0.60:50500
server:
  port: 9092

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true


